### ISSUE TITLE
Inserir Campos no TXT

### ISSUE THREAD

**Issue by kleiduda** [LeonardoBAV/iwish#2]
No TXT dos pedidos preciso incluir 2 campos novos:
Metodo de entrega: se parcial ou integral, ( passar apenas P ou I)
Observações do pedido: passar o texto completo.

**Comment by kleiduda** [comment]
[000001_0000008.txt](https://github.com/LeonardoBAV/iwish/files/1206404/000001_0000008.txt)

**Comment by LeonardoBAV** [comment]
Kleiton, podemos fechar esta issue?

**Comment by kleiduda** [comment]
Sim pode fechar
